apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    app: catalogue
    tier: app
    project: roboshop
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
      tier: app
      project: roboshop
  template: # from here onwards pod definition starts
    metadata:
      namespace: roboshop
      labels:
        app: catalogue
        tier: app
        project: roboshop
    spec:
      containers:
      - name: catalogue
        image: "shaiksuhail2767/catalogue:{{ .Values.deployment.ImageVersion }}"
        resources:
          requests:
            cpu: "50m"
            memory: "68Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        envFrom:
        - configMapRef:
            name: catalogue